### ISSUE TITLE
MudWorld.cs CurrentTimeOfDay never set before Load() is called.

### ISSUE THREAD

**Issue by danec020** [MudDesigner/MudEngine#3]
CurrentTimeOfDay is never set before the Load() method is executed and it has a private setter which prevents outside classes from setting the correct time.

**Comment by scionwest** [comment]
I spent some time working on this tonight and came to the conclusion that I really need to just migrate the entire time system over to the new adapter API. There are several issues with it right now.

1. In order to load a world, `MudWorld` needs to have it's `CurrentTimeOfDay` property set.
2. The `MudWorld.CurrentTimeOfDay` property depends on an instance of `ITimePeriod`
3. `TimePeriod` requires it's `StateStartTime` property to be set.
4. In order to set `StateStartTime`, you must start the time period by invokeing `Start()` and providing it with the initial `StartTime`.
5. This is bad as each world will have its timers started at different times during the life-cycle of the engine.

This can be solved by re-working how the `TimeManager` and `ITimePeriod` instances work together within the worlds. The [World Manager Adapter](https://github.com/MudDesigner/MudEngine/blob/master/Src/MudEngine.Game/Environment/WorldManager.cs#L51) needs to be finished. When it is finished, it can iterate over all of the worlds and start their individual Time of Day clocks at the same time.

**Comment by scionwest** [comment]
With 245ff0b3a1de5968b8a9935a0ee5d1d1228adcaf, you can get around this by creating a `TimeOfDay` with an initial start time, or by starting the timer on a `TimeOfDay`. You then provide that `TimeOfDay` instance to a `TimePeriod` that is given to a collection and provided to your `MudWorld`.

You can set the `StateStartTime` directly.

    var realWorldTimeOfDay = new TimeOfDay(DateTime.Now.Hour, DateTime.Now.Minute);
    var currentTimePeriod = new TimePeriod();

    // Set the StateStartTime directly
    currentTimePeriod.StateStartTime = realWorldTimeOfDay;

    var timePeriods = new List<ITimePeriod> { currentTimePeriod, };
    var world = new MudWorld(fooRealmFactory, timePeriods);

    await world.Initialize();

Or you can assign the start time by invoking `Start`

    var realWorldTimeOfDay = new TimeOfDay(DateTime.Now.Hour, DateTime.Now.Minute);
    var currentTimePeriod = new TimePeriod();

    // Start the time period clock with a specific start time provided.
    currentTimePeriod.Start(realWorldTimeOfDay, 4);

    var timePeriods = new List<ITimePeriod> { currentTimePeriod, };
    var world = new MudWorld(fooRealmFactory, timePeriods);

    await world.Initialize();

That should get you going again.
